// Misma lista y logica de busqueda que patitas-app/components/RazaAutocomplete.tsx,
// portada para no depender de un componente web.

const RAZAS_BASE = [
  'Mestizo',
  'Labrador Retriever',
  'Golden Retriever',
  'Pastor Alemán',
  'Caniche',
  'Caniche Toy',
  'Caniche Miniatura',
  'Bulldog Francés',
  'Beagle',
  'Poodle',
  'Rottweiler',
  'Yorkshire Terrier',
  'Dálmata',
  'Boxer',
  'Husky Siberiano',
  'Chihuahua',
  'Dachshund',
  'Dobermann',
  'Border Collie',
  'Cocker Spaniel',
  'Cocker Spaniel Inglés',
  'Cocker Spaniel Americano',
  'Shih Tzu',
  'Maltés',
  'Bichón Frisé',
  'Schnauzer',
  'Schnauzer Miniatura',
  'Schnauzer Gigante',
  'Pit Bull Terrier',
  'American Staffordshire Terrier',
  'Bull Terrier',
  'Shar Pei',
  'Samoyedo',
  'Akita',
  'Akita Americano',
  'Chow Chow',
  'Pomerania',
  'Spitz Alemán',
  'Gran Danés',
  'San Bernardo',
  'Terranova',
  'Setter Irlandés',
  'Pointer',
  'Weimaraner',
  'Vizsla',
  'Braco Alemán',
  'Pastor Belga Malinois',
  'Pastor Belga',
  'Pastor Australiano',
  'Border Terrier',
  'Jack Russell Terrier',
  'West Highland White Terrier',
  'Fox Terrier',
  'Pug',
  'Bulldog Inglés',
  'Boston Terrier',
  'Bullmastiff',
  'Mastín',
  'Mastín Napolitano',
  'Mastín Inglés',
  'Mastín Español',
  'Mastín del Pirineo',
  'Mastín del Tibet',
  'Fila Brasileño',
  'Dogo Argentino',
  'Dogo de Burdeos',
  'Dogo Canario',
  'Basset Hound',
  'Bloodhound',
  'Galgo',
  'Galgo Español',
  'Greyhound',
  'Whippet',
  'Borzoi',
  'Afghan Hound',
  'Saluki',
  'Malamute de Alaska',
  'Perro de Groenlandia',
  'Pekinés',
  'Lhasa Apso',
  'Rhodesian Ridgeback',
  'Basenji',
  'Cane Corso',
  'Boerboel',
  'Lagotto Romagnolo',
  'Spinone Italiano',
  'Airedale Terrier',
  'Bedlington Terrier',
  'Cavalier King Charles Spaniel',
  'King Charles Spaniel',
  'Collie',
  'Collie de Pelo Corto',
  'Shetland Sheepdog',
  'Old English Sheepdog',
  'Welsh Corgi Pembroke',
  'Welsh Corgi Cardigan',
  'Bouvier des Flandres',
  'Briard',
  'Leonberger',
  'Kuvasz',
  'Komondor',
  'Puli',
  'Nova Scotia Duck Tolling Retriever',
  'Flat-Coated Retriever',
  'Curly-Coated Retriever',
  'Perro de Agua Español',
  'Perro de Agua Portugués',
  'Presa Canario',
  'Tosa Inu',
  'Shiba Inu',
  'Spitz Japonés',
  'Hokkaido',
  'American Bully',
  'Staffordshire Bull Terrier',
  'Irish Terrier',
  'Kerry Blue Terrier',
  'Soft Coated Wheaten Terrier',
  'Dandie Dinmont Terrier',
  'Cairn Terrier',
  'Skye Terrier',
  'Norwich Terrier',
  'Norfolk Terrier',
  'Miniature Pinscher',
  'Affenpinscher',
  'Papillon',
  'Phalène',
  'Bichón Habanero',
  'Bolonka',
  'Coton de Tuléar',
  'Löwchen',
  'Xoloitzcuintle',
  "Cirneco dell'Etna",
  'Pharaoh Hound',
  'Ibizan Hound',
  'Azawakh',
  'Sloughi',
  'Chart Polski',
  'Hungarian Vizsla',
  'Irish Water Spaniel',
  'American Foxhound',
  'English Foxhound',
  'Harrier',
  'Otterhound',
  'Plott Hound',
  'Treeing Walker Coonhound',
  'Anatolian Shepherd',
  'Kangal',
  'Caucasian Shepherd',
  'Central Asian Shepherd',
  'Perro de Montaña de los Pirineos',
  'Perro de Montaña de Berna',
  'Appenzeller',
  'Entlebucher',
  'Hovawart',
  'Eurasier',
  'Finnish Spitz',
  'Laika Siberiano',
  'Saarlooswolfdog',
  'Czechoslovakian Wolfdog',
];

const ALIAS: Record<string, string> = {
  'mastin napolitano':   'Mastín Napolitano',
  'mastin napolitan':    'Mastín Napolitano',
  'napolitano':          'Mastín Napolitano',
  'napolitan':           'Mastín Napolitano',
  'mastino':             'Mastín Napolitano',
  'mastino napoletano':  'Mastín Napolitano',
  'ovejero':             'Pastor Alemán',
  'ovejero aleman':      'Pastor Alemán',
  'pastor aleman':       'Pastor Alemán',
  'perro policia':       'Pastor Alemán',
  'salchicha':           'Dachshund',
  'perro salchicha':     'Dachshund',
  'teckel':              'Dachshund',
  'basset aleman':       'Dachshund',
  'french poodle':       'Caniche',
  'caniche toy':         'Caniche Toy',
  'caniche enano':       'Caniche Miniatura',
  'caniche mini':        'Caniche Miniatura',
  'pitbull':             'Pit Bull Terrier',
  'pit':                 'Pit Bull Terrier',
  'pit bull':            'Pit Bull Terrier',
  'amstaff':             'American Staffordshire Terrier',
  'american staffordshire': 'American Staffordshire Terrier',
  'labrador':            'Labrador Retriever',
  'labrador negro':      'Labrador Retriever',
  'labrador chocolate':  'Labrador Retriever',
  'golden':              'Golden Retriever',
  'dogo':                'Dogo Argentino',
  'dogo arg':            'Dogo Argentino',
  'fila':                'Fila Brasileño',
  'fila brasilero':      'Fila Brasileño',
  'boxer':               'Boxer',
  'boxear':              'Boxer',
  'chihuahueño':         'Chihuahua',
  'chihuahena':          'Chihuahua',
  'bulldog':             'Bulldog Inglés',
  'bulldog ingles':      'Bulldog Inglés',
  'bulldog frances':     'Bulldog Francés',
  'francés':             'Bulldog Francés',
  'frances':             'Bulldog Francés',
  'husky':               'Husky Siberiano',
  'pomeranian':          'Pomerania',
  'pom':                 'Pomerania',
  'perro ardilla':       'Pomerania',
  'coker':               'Cocker Spaniel',
  'cocker':              'Cocker Spaniel',
  'schnauzer mini':      'Schnauzer Miniatura',
  'schnauzer enano':     'Schnauzer Miniatura',
  'schnauzer gigante':   'Schnauzer Gigante',
  'yorki':               'Yorkshire Terrier',
  'yorkie':              'Yorkshire Terrier',
  'yorkshire':           'Yorkshire Terrier',
  'maltes':              'Maltés',
  'shar-pei':            'Shar Pei',
  'charpei':             'Shar Pei',
  'carlino':             'Pug',
  'doberman':            'Dobermann',
  'dóberman':            'Dobermann',
  'rott':                'Rottweiler',
  'rotti':               'Rottweiler',
  'bigle':               'Beagle',
  'bichon':              'Bichón Frisé',
  'bichon frise':        'Bichón Frisé',
  'presa':               'Presa Canario',
  'dogo canario':        'Presa Canario',
  'cane corso':          'Cane Corso',
  'corso':               'Cane Corso',
  'bully':               'American Bully',
  'am bully':            'American Bully',
  'danes':               'Gran Danés',
  'gran danes':          'Gran Danés',
  'great dane':          'Gran Danés',
  'malamute':            'Malamute de Alaska',
  'lassie':              'Collie',
  'shiba':               'Shiba Inu',
  'jack':                'Jack Russell Terrier',
  'jack russell':        'Jack Russell Terrier',
  'westie':              'West Highland White Terrier',
  'west highland':       'West Highland White Terrier',
  'braco weimar':        'Weimaraner',
  'mastin ingles':       'Mastín Inglés',
  'malinois':            'Pastor Belga Malinois',
  'mali':                'Pastor Belga Malinois',
  'aussie':              'Pastor Australiano',
  'border':              'Border Collie',
  'samoyed':             'Samoyedo',
  'perro de agua':       'Perro de Agua Español',
  'water dog':           'Perro de Agua Español',
  'san huberto':         'Bloodhound',
  'bobtail':             'Old English Sheepdog',
  'galgo afgano':        'Afghan Hound',
  'galgo español':       'Galgo Español',
};

function norm(s: string) {
  return s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
}

export function buscarRazas(query: string): string[] {
  if (!query.trim()) return RAZAS_BASE;

  const q = norm(query);
  const resultados = new Set<string>();

  for (const r of RAZAS_BASE) {
    if (norm(r).includes(q)) resultados.add(r);
  }

  for (const [alias, canonica] of Object.entries(ALIAS)) {
    if (norm(alias).includes(q) || q.includes(norm(alias))) {
      resultados.add(canonica);
    }
  }

  if (resultados.size === 0) {
    const palabras = q.split(/\s+/).filter((p) => p.length > 2);
    for (const r of RAZAS_BASE) {
      if (palabras.some((p) => norm(r).includes(p))) resultados.add(r);
    }
  }

  return [...resultados].sort();
}

export const COLORES_PERRO: string[] = [
  'Negro',
  'Blanco',
  'Marrón',
  'Caramelo',
  'Dorado',
  'Gris',
  'Atigrado',
  'Tricolor',
  'Manchado',
  'Canela',
];
